---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, nfsv3 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. 
---
= Bekannte Einschränkungen in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen bei allen Cloud-Providern"].



== Einschränkungen für Flash Cache

Der VM-Typ Standard_L8S_v2 umfasst lokalen NVMe-Storage, den Cloud Volumes ONTAP als _Flash Cache_ verwendet. Beachten Sie die folgenden Einschränkungen für Flash Cache:

* Um die Performance-Verbesserungen von Flash Cache nutzen zu können, muss die Komprimierung für alle Volumes deaktiviert sein.
+
Beim Erstellen eines Volumes aus Cloud Manager kann keine Storage-Effizienz gewählt werden. Alternativ können Sie ein Volume erstellen und dann http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deaktivieren Sie die Datenkomprimierung über die CLI"^].

* Cloud Volumes ONTAP unterstützt das Neustarten des Cache nicht, wenn ein Neustart nach einem Neustart erfolgen soll.




== HA-Einschränkungen

Die folgenden Einschränkungen betreffen Cloud Volumes ONTAP HA-Paare in Microsoft Azure:

* NFSv4 wird nicht unterstützt. NFSv3 wird unterstützt.
* HA-Paare werden in einigen Regionen nicht unterstützt.
+
https://cloud.netapp.com/cloud-volumes-global-regions["Siehe die Liste der unterstützten Azure Regionen"^]


