---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.9.1 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.9.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.9.1 enthält mehrere neue Funktionen und Verbesserungen.

Zusätzliche Funktionen und Verbesserungen sind auch in den neuesten Versionen von Cloud Manager eingeführt. Siehe https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Versionshinweise Zu Cloud Manager"^] Entsprechende Details.



== c4-, m4- und r4-Instanzen werden nicht mehr unterstützt (28. Oktober 2022)

In AWS werden die Instanztypen c4, m4 und r4 EC2 nicht mehr mit Cloud Volumes ONTAP unterstützt. Wenn Sie bereits ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 auf einen Instanztyp wechseln.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.



== 9.9.1 P8 (15. Mai 2022)

Der Patch 9.9.1 P8 ist nun für Cloud Volumes ONTAP in Microsoft Azure verfügbar, wenn Sie über einen Connector mit Version 3.9.13 oder höher verfügen. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P8["Zeigen Sie die Liste der im P8-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.9.1 P7 (21. Februar 2022)

Der Patch 9.9.1 P7 steht jetzt für Cloud Volumes ONTAP in Microsoft Azure zur Verfügung, wenn Sie über einen Connector mit Version 3.9.15 oder höher verfügen. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P7["Zeigen Sie die Liste der im P7-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.9.1 Patches (3. Februar 2022)

Für Cloud Volumes ONTAP sind zwei neue Patches verfügbar:

* 9.9.1 P6 in AWS und Google Cloud
* 9.9.1 P3 in Microsoft Azure


Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Releases zu aktualisieren.

* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P6["Zeigen Sie die Liste der im P6-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich)
* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P3["Zeigen Sie die Liste der im P3-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich)




== 9.9.1 GA (21. Juli 2021)

Das Release von Cloud Volumes ONTAP 9.9.1 (General Availability, GA) ist jetzt verfügbar. Die GA-Version enthält Bug Fixes.

Cloud Manager fordert Sie auf, bestehende Systeme mit einer der folgenden Versionen zu aktualisieren: 9.9.1 Release Candidate, 9.9.0 oder 9.8.



== Update 9.9.1 (7. Juli 2021)

Die folgenden Änderungen wurden mit Version Cloud Manager 3.9.8 eingeführt.

* Für Cloud Volumes ONTAP stehen neue Lademethoden zur Verfügung.
+
** *Kapazitätsbasiertes BYOL*: Eine kapazitätsbasierte Lizenz ermöglicht die Zahlung von Cloud Volumes ONTAP pro tib Kapazität. Die Lizenz ist mit Ihrem NetApp Konto verknüpft und ermöglicht es Ihnen, mehrere Cloud Volumes ONTAP-Systeme zu erstellen, solange über Ihre Lizenz genügend Kapazität verfügbar ist. Kapazitätsbasierte Lizenzierung ist in Form eines Pakets verfügbar, entweder _Essentials_ oder _Professional_.
** *Freimium Angebot*: Mit Freimium können Sie alle Cloud Volumes ONTAP Funktionen kostenlos von NetApp nutzen (Cloud-Provider fallen weiterhin an). Sie verfügen über eine zugewiesene Kapazität von 500 gib pro System. Es besteht kein Support-Vertrag. Sie können bis zu 10 Freemium-Systeme haben.
+
link:concept-licensing.html["Erfahren Sie mehr über diese Lizenzierungsoptionen"].



* In AWS unterstützt Cloud Volumes ONTAP jetzt den Instanztyp m5dn.24xlarge mit den folgenden Lademethoden: PAYGO Premium, kapazitätsbasierte Lizenzen (BYOL) und Node-basierte Lizenzen (BYOL).
* In Google Cloud unterstützt Cloud Volumes ONTAP jetzt ausgeglichene persistente Festplatten (pd-ausgewogen). Diese SSDs sorgen mit weniger IOPS pro gib für ausgewogene Performance und Kosten.
* Der Maschinentyp Custom-4-16384 wird von neuen Cloud Volumes ONTAP-Systemen in Google Cloud nicht mehr unterstützt.
+
Wenn auf diesem Maschinentyp ein System ausgeführt wird, können Sie es weiterhin verwenden, wir empfehlen jedoch, auf den Maschinentyp n2-Standard-4 umzuschalten.



https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Erfahren Sie mehr über die Neuerungen in Cloud Manager"^].



== Update 9.9.1 (3. Juni 2021)

Mit dem kürzlich veröffentlichten Release Cloud Manager 3.9.7 wird auch ein neues Professional-Paket unterstützt, mit dem Sie Cloud Volumes ONTAP und Cloud Backup Service unter Verwendung eines Jahresvertrags im AWS Marketplace bündeln können.

link:reference-configs-aws.html["Erfahren Sie mehr über diese Lizenzoption."]



== Release Candidate 9.9.1 (24. Mai 2021)

Der Cloud Volumes ONTAP 9.9.1 Release Candidate ist jetzt in AWS, Azure und Google Cloud Platform verfügbar.

Zusätzlich zu den bereits mit eingeführten Funktionen https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.9.1"^], Diese Version von Cloud Volumes ONTAP enthält die folgenden:

* <<Unterstützung von ONTAP S3 in Azure>>
* <<Verbesserte Performance in AWS mit hoher Schreibgeschwindigkeit>>
* <<io2-Boot-Disk in AWS>>




=== Unterstützung von ONTAP S3 in Azure

Sie können jetzt S3-Objekt-Storage von Cloud Volumes ONTAP in Azure bereitstellen. Cloud Volumes ONTAP für Microsoft Azure unterstützt S3 als Option für Scale-out Storage neben klassischen dateibasierten Protokollen wie NFS und SMB.

Beachten Sie Folgendes:

* Der Hauptanwendungsfall für ONTAP S3 mit Cloud Volumes ONTAP ist ein allgemeiner Objektspeicher.
* Derzeit wird das S3-Protokoll nicht mit Cloud Volumes ONTAP in AWS oder in der Google Cloud unterstützt.
* Cloud Manager bietet keine Managementfunktionen für die ONTAP S3 Funktion.


Als Best Practice empfiehlt sich die Konfiguration des S3-Client-Zugriffs über Cloud Volumes ONTAP mithilfe der CLI. Weitere Informationen finden Sie im http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 Configuration Power Guide"^].



=== Verbesserte Performance in AWS mit hoher Schreibgeschwindigkeit

Wir haben die Durchsatz-Performance von Cloud Volumes ONTAP wann erweitert https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["Hohe Schreibgeschwindigkeit"^] Ist auf einem unterstützten Instanztyp aktiviert.



=== io2-Boot-Disk in AWS

In AWS ist die Boot-Festplatte für ein neues Cloud Volumes ONTAP System jetzt ein IOPS-SSD (io2)-Volume bereitgestellt. io2-Volumen bieten eine höhere Zuverlässigkeit als io1-Volumen, die zuvor für Boot-Disks verwendet wurden.



== Erforderliche Version des Cloud Manager Connectors

Der Cloud Manager Connector muss Version 3.9.6 oder höher ausführen, um neue Cloud Volumes ONTAP 9.9.1-Systeme bereitzustellen und bestehende Systeme auf 9.9 zu aktualisieren.



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von Cloud Manager abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.9.0 und Version 9.8 auf Cloud Volumes ONTAP 9.9.1 durchführen. Cloud Manager fordert Sie zum Upgrade Ihrer vorhandenen Cloud Volumes ONTAP 9.9.0- und 9.8-Systeme auf Version 9.9.1 auf.
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Informieren Sie sich, wie ein Upgrade durchgeführt wird, wenn Cloud Manager Sie benachrichtigt"^].

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.




=== DS3_v2

Ab der Version 9.9.1 wird der DS3_v2 VM-Typ nicht mehr mit neuen und vorhandenen Cloud Volumes ONTAP-Systemen unterstützt. Wenn auf diesem VM-Typ ein System ausgeführt wird, müssen Sie VM-Typen ändern, bevor Sie auf 9.9 aktualisieren.
